[2022-03-24 15:50:56,014] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.ExampleValidator manual__2022-03-24T15:42:29.578379+00:00 [queued]>
[2022-03-24 15:50:56,020] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.ExampleValidator manual__2022-03-24T15:42:29.578379+00:00 [queued]>
[2022-03-24 15:50:56,020] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:50:56,020] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 15:50:56,020] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:50:56,028] {taskinstance.py:1264} INFO - Executing <Task(AirflowComponent): ExampleValidator> on 2022-03-24 15:42:29.578379+00:00
[2022-03-24 15:50:56,046] {standard_task_runner.py:52} INFO - Started process 756 to run task
[2022-03-24 15:50:56,049] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'census_consumer_complaint', 'ExampleValidator', 'manual__2022-03-24T15:42:29.578379+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/census_consumer_complaint.py', '--cfg-path', '/tmp/tmp65prowob', '--error-file', '/tmp/tmp7bhczzdl']
[2022-03-24 15:50:56,050] {standard_task_runner.py:77} INFO - Job 60: Subtask ExampleValidator
[2022-03-24 15:50:56,093] {logging_mixin.py:109} INFO - Running <TaskInstance: census_consumer_complaint.ExampleValidator manual__2022-03-24T15:42:29.578379+00:00 [running]> on host 691464fec4e5
[2022-03-24 15:50:56,131] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=census_consumer_complaint
AIRFLOW_CTX_TASK_ID=ExampleValidator
AIRFLOW_CTX_EXECUTION_DATE=2022-03-24T15:42:29.578379+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-24T15:42:29.578379+00:00
[2022-03-24 15:50:56,133] {base_component_launcher.py:190} INFO - Running driver for ExampleValidator
[2022-03-24 15:50:56,138] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:50:56,157] {base_component_launcher.py:196} INFO - Running executor for ExampleValidator
[2022-03-24 15:50:56,167] {executor.py:95} INFO - Validating schema against the computed statistics for split train.
[2022-03-24 15:50:56,181] {executor.py:113} INFO - Validation complete for split train. Anomalies written to /opt/***/census_consumer_complaint_data/census_consumer_complaint/artifact/ExampleValidator/anomalies/9/Split-train.
[2022-03-24 15:50:56,181] {executor.py:95} INFO - Validating schema against the computed statistics for split eval.
[2022-03-24 15:50:56,194] {executor.py:113} INFO - Validation complete for split eval. Anomalies written to /opt/***/census_consumer_complaint_data/census_consumer_complaint/artifact/ExampleValidator/anomalies/9/Split-eval.
[2022-03-24 15:50:56,195] {base_component_launcher.py:206} INFO - Running publisher for ExampleValidator
[2022-03-24 15:50:56,197] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:50:56,200] {python.py:175} INFO - Done. Returned value was: None
[2022-03-24 15:50:56,209] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=census_consumer_complaint, task_id=ExampleValidator, execution_date=20220324T154229, start_date=20220324T155056, end_date=20220324T155056
[2022-03-24 15:50:56,260] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-24 15:50:56,278] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
