[2022-03-24 16:01:06,889] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.Pusher manual__2022-03-24T15:42:29.578379+00:00 [queued]>
[2022-03-24 16:01:06,895] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.Pusher manual__2022-03-24T15:42:29.578379+00:00 [queued]>
[2022-03-24 16:01:06,895] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 16:01:06,895] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 16:01:06,895] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 16:01:06,900] {taskinstance.py:1264} INFO - Executing <Task(AirflowComponent): Pusher> on 2022-03-24 15:42:29.578379+00:00
[2022-03-24 16:01:06,916] {standard_task_runner.py:52} INFO - Started process 1715 to run task
[2022-03-24 16:01:06,918] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'census_consumer_complaint', 'Pusher', 'manual__2022-03-24T15:42:29.578379+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/census_consumer_complaint.py', '--cfg-path', '/tmp/tmp2swsoyxz', '--error-file', '/tmp/tmp9k3v6pt4']
[2022-03-24 16:01:06,918] {standard_task_runner.py:77} INFO - Job 64: Subtask Pusher
[2022-03-24 16:01:06,948] {logging_mixin.py:109} INFO - Running <TaskInstance: census_consumer_complaint.Pusher manual__2022-03-24T15:42:29.578379+00:00 [running]> on host 691464fec4e5
[2022-03-24 16:01:06,975] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=census_consumer_complaint
AIRFLOW_CTX_TASK_ID=Pusher
AIRFLOW_CTX_EXECUTION_DATE=2022-03-24T15:42:29.578379+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-24T15:42:29.578379+00:00
[2022-03-24 16:01:06,976] {base_component_launcher.py:190} INFO - Running driver for Pusher
[2022-03-24 16:01:06,978] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 16:01:06,990] {base_component_launcher.py:196} INFO - Running executor for Pusher
[2022-03-24 16:01:06,992] {executor.py:87} INFO - Model on /opt/***/census_consumer_complaint_data/census_consumer_complaint/artifact/Evaluator/blessing/12 was not blessed by model validation
[2022-03-24 16:01:06,992] {base_component_launcher.py:206} INFO - Running publisher for Pusher
[2022-03-24 16:01:06,993] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 16:01:06,996] {python.py:175} INFO - Done. Returned value was: None
[2022-03-24 16:01:07,003] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=census_consumer_complaint, task_id=Pusher, execution_date=20220324T154229, start_date=20220324T160106, end_date=20220324T160107
[2022-03-24 16:01:07,049] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-24 16:01:07,090] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
