[2022-03-27 14:11:04,260] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.latest_blessed_model_resolver manual__2022-03-27T14:10:57.831445+00:00 [queued]>
[2022-03-27 14:11:04,268] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.latest_blessed_model_resolver manual__2022-03-27T14:10:57.831445+00:00 [queued]>
[2022-03-27 14:11:04,268] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 14:11:04,268] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-27 14:11:04,268] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-27 14:11:04,276] {taskinstance.py:1264} INFO - Executing <Task(AirflowComponent): latest_blessed_model_resolver> on 2022-03-27 14:10:57.831445+00:00
[2022-03-27 14:11:04,284] {standard_task_runner.py:52} INFO - Started process 133 to run task
[2022-03-27 14:11:04,287] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'census_consumer_complaint', 'latest_blessed_model_resolver', 'manual__2022-03-27T14:10:57.831445+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/census_consumer_complaint.py', '--cfg-path', '/tmp/tmpnjzwg6ft', '--error-file', '/tmp/tmppqh22rvh']
[2022-03-27 14:11:04,287] {standard_task_runner.py:77} INFO - Job 143: Subtask latest_blessed_model_resolver
[2022-03-27 14:11:04,327] {logging_mixin.py:109} INFO - Running <TaskInstance: census_consumer_complaint.latest_blessed_model_resolver manual__2022-03-27T14:10:57.831445+00:00 [running]> on host 691464fec4e5
[2022-03-27 14:11:04,359] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=census_consumer_complaint
AIRFLOW_CTX_TASK_ID=latest_blessed_model_resolver
AIRFLOW_CTX_EXECUTION_DATE=2022-03-27T14:10:57.831445+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-27T14:10:57.831445+00:00
[2022-03-27 14:11:04,360] {base_component_launcher.py:190} INFO - Running driver for latest_blessed_model_resolver
[2022-03-27 14:11:04,364] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-27 14:11:04,378] {base_component_launcher.py:206} INFO - Running publisher for latest_blessed_model_resolver
[2022-03-27 14:11:04,380] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-27 14:11:04,381] {python.py:175} INFO - Done. Returned value was: None
[2022-03-27 14:11:04,391] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=census_consumer_complaint, task_id=latest_blessed_model_resolver, execution_date=20220327T141057, start_date=20220327T141104, end_date=20220327T141104
[2022-03-27 14:11:04,418] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-27 14:11:04,445] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
