[2022-03-24 15:42:39,277] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.latest_blessed_model_resolver scheduled__2022-03-23T00:00:00+00:00 [queued]>
[2022-03-24 15:42:39,292] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.latest_blessed_model_resolver scheduled__2022-03-23T00:00:00+00:00 [queued]>
[2022-03-24 15:42:39,292] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:42:39,292] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 15:42:39,292] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:42:39,303] {taskinstance.py:1264} INFO - Executing <Task(AirflowComponent): latest_blessed_model_resolver> on 2022-03-23 00:00:00+00:00
[2022-03-24 15:42:39,318] {standard_task_runner.py:52} INFO - Started process 228 to run task
[2022-03-24 15:42:39,324] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'census_consumer_complaint', 'latest_blessed_model_resolver', 'scheduled__2022-03-23T00:00:00+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/census_consumer_complaint.py', '--cfg-path', '/tmp/tmpyvkjdo12', '--error-file', '/tmp/tmpd__1g0up']
[2022-03-24 15:42:39,324] {standard_task_runner.py:77} INFO - Job 52: Subtask latest_blessed_model_resolver
[2022-03-24 15:42:39,366] {logging_mixin.py:109} INFO - Running <TaskInstance: census_consumer_complaint.latest_blessed_model_resolver scheduled__2022-03-23T00:00:00+00:00 [running]> on host 691464fec4e5
[2022-03-24 15:42:39,417] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=census_consumer_complaint
AIRFLOW_CTX_TASK_ID=latest_blessed_model_resolver
AIRFLOW_CTX_EXECUTION_DATE=2022-03-23T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-03-23T00:00:00+00:00
[2022-03-24 15:42:39,419] {base_component_launcher.py:190} INFO - Running driver for latest_blessed_model_resolver
[2022-03-24 15:42:39,429] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:42:39,447] {base_component_launcher.py:206} INFO - Running publisher for latest_blessed_model_resolver
[2022-03-24 15:42:39,450] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:42:39,451] {python.py:175} INFO - Done. Returned value was: None
[2022-03-24 15:42:39,461] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=census_consumer_complaint, task_id=latest_blessed_model_resolver, execution_date=20220323T000000, start_date=20220324T154239, end_date=20220324T154239
[2022-03-24 15:42:39,492] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-24 15:42:39,520] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
