[2022-03-24 15:50:50,879] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.SchemaGen manual__2022-03-24T15:42:29.578379+00:00 [queued]>
[2022-03-24 15:50:50,884] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: census_consumer_complaint.SchemaGen manual__2022-03-24T15:42:29.578379+00:00 [queued]>
[2022-03-24 15:50:50,885] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:50:50,885] {taskinstance.py:1244} INFO - Starting attempt 1 of 1
[2022-03-24 15:50:50,885] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-03-24 15:50:50,891] {taskinstance.py:1264} INFO - Executing <Task(AirflowComponent): SchemaGen> on 2022-03-24 15:42:29.578379+00:00
[2022-03-24 15:50:50,905] {standard_task_runner.py:52} INFO - Started process 725 to run task
[2022-03-24 15:50:50,907] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'census_consumer_complaint', 'SchemaGen', 'manual__2022-03-24T15:42:29.578379+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/census_consumer_complaint.py', '--cfg-path', '/tmp/tmp7ffymb1i', '--error-file', '/tmp/tmpi8zsimwy']
[2022-03-24 15:50:50,908] {standard_task_runner.py:77} INFO - Job 59: Subtask SchemaGen
[2022-03-24 15:50:50,936] {logging_mixin.py:109} INFO - Running <TaskInstance: census_consumer_complaint.SchemaGen manual__2022-03-24T15:42:29.578379+00:00 [running]> on host 691464fec4e5
[2022-03-24 15:50:50,964] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=census_consumer_complaint
AIRFLOW_CTX_TASK_ID=SchemaGen
AIRFLOW_CTX_EXECUTION_DATE=2022-03-24T15:42:29.578379+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-03-24T15:42:29.578379+00:00
[2022-03-24 15:50:50,964] {base_component_launcher.py:190} INFO - Running driver for SchemaGen
[2022-03-24 15:50:50,967] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:50:50,979] {base_component_launcher.py:196} INFO - Running executor for SchemaGen
[2022-03-24 15:50:50,979] {executor.py:78} INFO - Processing schema from statistics for split train.
[2022-03-24 15:50:50,997] {executor.py:78} INFO - Processing schema from statistics for split eval.
[2022-03-24 15:50:51,010] {executor.py:96} INFO - Schema written to /opt/***/census_consumer_complaint_data/census_consumer_complaint/artifact/SchemaGen/schema/8/schema.pbtxt.
[2022-03-24 15:50:51,011] {base_component_launcher.py:206} INFO - Running publisher for SchemaGen
[2022-03-24 15:50:51,012] {metadata_store.py:101} INFO - MetadataStore with DB connection initialized
[2022-03-24 15:50:51,015] {python.py:175} INFO - Done. Returned value was: None
[2022-03-24 15:50:51,023] {taskinstance.py:1282} INFO - Marking task as SUCCESS. dag_id=census_consumer_complaint, task_id=SchemaGen, execution_date=20220324T154229, start_date=20220324T155050, end_date=20220324T155051
[2022-03-24 15:50:51,078] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-24 15:50:51,102] {local_task_job.py:264} INFO - 2 downstream tasks scheduled from follow-on schedule check
